### ISSUE TITLE
小程序如何修改代码与看页面同步

### ISSUE THREAD

**Issue by dislazy** [zhaoo/hexo-weapp-zhaoo#13]
作者您好：
     感谢您的开源小程序，我这边正准备使用您的小程序作为我的小程序，但是因为我的博客中没有封面图什么的，然后导致小程序各种报错，但是呢也不知道怎么调试（后端一枚），能看懂代码，修改一些简单代码，但是每次修改完都需要重新build才能展示，有没有办法能够修改完直接显示嘛。我的博客json：https://blog.bosong.online/api/posts/1.json

感谢作者。

**Comment by zhaoo** [comment]
小程序调试模式：yarn dev:weapp

**Comment by zhaoo** [comment]
建议还是加一点封面
